### ISSUE TITLE
`Bad Schandau Leipzig` fails with "Bahnhof nicht gefunden! (Baden-Baden schandau leipzig)".

### ISSUE THREAD

**Issue by dreirund** [k0nte/bahn#1]
When I want to search from `Bad Schandau`, the system seems to interpret `Bad` as "Baden-Baden" and then fails subsequently.

Using `Bad-Schandau` as a workaround works, but is technically incorrect (the place is called "Bad Schandau", not "Bad-Schandau").

Example:  
Input query:  
`Bad Schandau Leipzig`

Error message:  
`Bahnhof nicht gefunden! (Baden-Baden schandau leipzig)`

Regards!

**Comment by k0nte** [comment]
Korrigiert, danke!

**Comment by dreirund** [comment]
Es scheint nicht einfach zu sein Orte der Art "Bad <x>" von
"BAD"="Baden-Baden" zu unterscheiden.

Test cases:

* `Bad Schandau Bad Mergentheim` --> Verbindungsauskunft zwischen
  "Bad Schandau" und "Bad Mergentheim".
* `Bad Schandau Bad` --> https://www.bahnhof.de/bad-schandau
* `Bad Schandau BAD` --> Verbindungsauskunft zwischen
  "Bad Schandau" und "Baden-Baden".
* `Bad Bad Schandau` --> Verbindungsauskunft zwischen
  "Basel Badischer Bahnhof" und "Bad Schandau".
* `Bad Bad` --> Verbindungsauskunft zwischen
  "Basel Badischer Bahnhof" und "Bad Schandau".

**Comment by k0nte** [comment]
Das stimmt, aber die Idee ist, dass der beste Fund gewählt wird. "Bad" als Ort wird nicht gefunden, deshalb ist `Bad Bad Schandau` schwierig. Das wird aufgelöst als `Bad Bad -> Schandau`. Die Abkürzung ist jetzt auf Großbuchstaben begrenzt, `BAD Bad Schandau` klappt also. `Bad nach Bad Schandau` wird nicht gefunden. 

Ich sehe da keinen Änderungsbedarf, weil "Bad" als Wort auf jeden Fall wichtiger ist als die Abkürzung, die ja weiterhin erreichbar ist. Gibt noch ein paar andere Abkürzungen wie Do=Donnerstag, DO=Dortmund, bei der eine Unterscheidung nötig ist.
