### ISSUE TITLE
[Feature Request] Allow "Leitpunktkürzel".

### ISSUE THREAD

**Issue by dreirund** [k0nte/bahn#2]
Ahoj,

I hereby have the feature request to also allow for the abbreviations given in the routing information of tickets.

E.g.

* `BSU` &rarr; "Bad Schandau"
* `BSK` &rarr; "Berlin Südkreuz"

etc.

This are the shorthand abbreviations I remember (because I regularly see them on tickets) and usually also use. [bahn.de](http://bahn.de/) also understands many (not all) of them.

Regards!

**Comment by k0nte** [comment]
Gibt es Kollisionen zwischen Leitpunktkürzeln und Betriebsstellenkürzeln?
Meine Überlegung wäre, eine Einstellung dafür einzuführen, "Erweitert" oder so (wie BC25) und in dem Fall würden diese Kürzel bevorzugt ausgelesen werden. 

Und gibt es Listen dieser Kürzel z.B. als Excel-Datei? Das würde helfen, ansonsten wäre die Einpflegung etwas mühsam. Ich habe sie zumindest hier gefunden, aber vielleicht gibt es ja noch bessere Listen (z.B. alles auf einer Internetseite):
https://assets.static-bahn.de/dam/jcr:9567b116-c600-4594-89a6-687259817dec/Leitpunktkuerzel.pdf
https://www.bahnseite.de/DS100/DS100_main.html

PS: Ich bleibe mal bei Deutsch, ich glaube nicht, dass die Seite in Zukunft für ein nichtdeutsches Publikum relevant sein wird ... :)

**Comment by k0nte** [comment]
Es gibt wohl einige Kollisionen, z.B. Leitpunkt `AN` = Ansbach /  Betriebsstelle `AN` = Neumünster
Ich habe die Listen mal eingearbeitet in die Datei punkte.php. Die Frage ist, sollen Leitpunkte einfach Betriebsstellen überschreiben? Oder sollte die Suche nach beiden möglich sein? Z.B. mit `b:AN` / `l:AN`

**Comment by dreirund** [comment]
Ahoj,

On Thu, 18 Jan 2024 04:13:28 -0800, k0nte ***@***.***>
wrote:

> Und gibt es Listen dieser Kürzel z.B. als Excel-Datei?

Mir ist auch nur

> https://assets.static-bahn.de/dam/jcr:9567b116-c600-4594-89a6-687259817dec/Leitpunktkuerzel.pdf

eine PDF-Datei bekannt.

> Es gibt wohl einige Kollisionen, z.B. Leitpunkt `AN` = Ansbach /
> Betriebsstelle `AN` = Neumünster
> Ich habe die Listen mal eingearbeitet in die Datei punkte.php. Die
> Frage ist, sollen Leitpunkte einfach Betriebsstellen überschreiben?
> Oder sollte die Suche nach beiden möglich sein? Z.B. mit `b:AN` /
> `l:AN`

Da sich sicherlich einige beschweren würden wenn
Betriebssstellenkürzel nicht zugänglich sind wenn es Leitpunktkürzel
gibt, würde ich mit entsprechendem Präfix wie vorgeschlagen beides
akzeptieren.

Ohne Präfix sollte eines das andere überschreiben -- sinnvoll finde ich
da:

* KFZ-Kennzeichen > Leitpunkt > Betriebsstelle.

(Rationale: KFZ-Kennzeichen ist im Zweifel am bekanntesten bei
nicht-Bahn-Affinen. Leitpunktkürzel begegnen der nicht betrieblich
interessierten Person, die sich ihre Fahrkarten anschaut, auch.)

**Comment by k0nte** [comment]
Es sollte jetzt klappen.
Die Reihenfolge ist:
KFZ-Kennzeichen > Normale Suche > Leitpunkt > Betriebsstelle

Dazu gibt es mehrere Möglichkeiten, Leitpunkte bzw. Betriebsstellen zuerst zu suchen:
`l:bsu b:an` – Präfix (Bad Schandau nach Neumünster)
`bsu AN Betriebsstelle` (oder `Leitpunkt`) – gilt für Start und Ziel (Schwarze Pumpe nach Neumünster)
Per Einstellung bei ⚙. Wie oben für Start und Ziel, kann durch Eingaben überschrieben werden, es gibt aber keine Eingabe für KFZ-Kennzeichen.

Bei all diesen Wegen ist die Reihenfolge:
Leitpunkt/Betriebsstelle > Betriebsstelle/Leitpunkt > KFZ-Kennzeichen > Normale Suche.

Eine Vermischung ist also möglich, z.B.:
`bsu hx` Leitpunkt > KFZ
`Leitpunkt AN Frankfurt` Leitpunkt -> Suche (Ansbach -> Frankfurt Hbf)
`b:bsu AN` Betriebsstelle -> Leitpunkt (Schwarze Pumpe -> Ansbach)
(`AN` muss groß sein, damit es nicht als Schlüsselwort für `an 15:00 Uhr` erkannt wird.)

Ich hoffe, es klappt alles!

**Comment by dreirund** [comment]
Schön, danke!
