### ISSUE TITLE
Zugsuche scheint nicht zu funtionieren: `EC 6` leitet weiter nach https://www.bahnhof.de/ecaussinnes.

### ISSUE THREAD

**Issue by dreirund** [k0nte/bahn#4]
Im Beispiel steht  
> *ICE 722      = Zuginformationen*

Wenn ich [`EC 6` eingebe](https://bahnu.de/?xq=EC%206) dann werde ich weitergeleitet nach [https://www.bahnhof.de/ecaussinnes](https://www.bahnhof.de/ecaussinnes).

**Comment by k0nte** [comment]
Ist korrigiert (für einstellige Zugnummern).
Gerne auch zurückmelden, falls man zu falschen Zügen bei zugfinder.net weitergeleitet wird. Da bin ich mir manchmal nicht so sicher.
